// Fill out your copyright notice in the Description page of Project Settings.


#include "CharacterControllerBase.h"
#include "EnhancedInputComponent.h"
#include "EnhancedInputSubsystems.h"
#include "InputMappingContext.h"
#include "CharacterBase.h"
#include "CameraCenterActor.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "Kismet/GameplayStatics.h"
#include "GameMode_LevelBase.h"
#include "WBP_LevelUIBase.h"


void ACharacterControllerBase::BeginPlay()
{
	Super::BeginPlay();

	SetViewTarget(CameraCenterActor);

	// âœ… ç›´æ¥åŒæ­¥å»ºç«‹ UIï¼Œä¸ç”¨ AsyncTask
	if (LevelUIClass)
	{
		LevelUIInstance = CreateWidget<UWBP_LevelUIBase>(this, LevelUIClass);
		if (LevelUIInstance)
		{
			LevelUIInstance->AddToViewport();
			LevelUIInstance->SetDiamondCount(0);
			LevelUIInstance->SetCoinCount(0);
			LevelUIInstance->SetTime(0);
			UE_LOG(LogTemp, Warning, TEXT("ğŸŸ¢ UI Created Successfully"));
		}
		else
		{
			UE_LOG(LogTemp, Error, TEXT("âŒ UI creation failed"));
		}
	}

	// âœ… é–‹å§‹æ¯ç§’æ›´æ–° UI
	GetWorldTimerManager().SetTimer(
		TimerHandle_UpdateTime,
		this,
		&ACharacterControllerBase::UpdateLevelUI,
		1.0f,
		true
	);
}

void ACharacterControllerBase::SetupInputComponent()
{
	Super::SetupInputComponent();

	TObjectPtr<UEnhancedInputComponent> EnhancedInputComponent
		= Cast<UEnhancedInputComponent>(this->InputComponent);

	if (EnhancedInputComponent)
	{
		// ç§»å‹•å…¥åŠ›
		EnhancedInputComponent->BindAction(MoveAction.Get(),
			ETriggerEvent::Triggered,
			this, &ACharacterControllerBase::Move);

		// è¦–ç‚¹æ“ä½œ
		EnhancedInputComponent->BindAction(LookAction.Get(),
			ETriggerEvent::Triggered,
			this, &ACharacterControllerBase::Look);

		// ãƒ€ãƒƒã‚·ãƒ¥é–‹å§‹
		EnhancedInputComponent->BindAction(RunAction.Get(),
			ETriggerEvent::Started,
			this, &ACharacterControllerBase::RunStart);

		// ãƒ€ãƒƒã‚·ãƒ¥çµ‚äº†
		EnhancedInputComponent->BindAction(RunAction.Get(),
			ETriggerEvent::Completed,
			this, &ACharacterControllerBase::RunStop);

		// ã‚ºãƒ¼ãƒ åˆ‡ã‚Šæ›¿ãˆ
		EnhancedInputComponent->BindAction(ZoomAction.Get(),
			ETriggerEvent::Started,
			this, &ACharacterControllerBase::HandleZoom);

		// ã‚¤ãƒ³ã‚¿ãƒ©ã‚¯ãƒˆå®Ÿè¡Œï¼ˆãƒœã‚¿ãƒ³ã§ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã‚’æ“ä½œï¼‰
		EnhancedInputComponent->BindAction(InteractAction.Get(),
			ETriggerEvent::Started,
			this, &ACharacterControllerBase::HandleInteract);

		// ãƒãƒ¼ãƒãƒ£ãƒ«ã‚«ãƒ¼ã‚½ãƒ«æœ‰åŠ¹åŒ–
		EnhancedInputComponent->BindAction(ToggleCursorAction.Get(),
			ETriggerEvent::Started,
			this, &ACharacterControllerBase::HandleCursorPressed);

		// ãƒãƒ¼ãƒãƒ£ãƒ«ã‚«ãƒ¼ã‚½ãƒ«ç„¡åŠ¹åŒ–
		EnhancedInputComponent->BindAction(ToggleCursorAction.Get(),
			ETriggerEvent::Completed,
			this, &ACharacterControllerBase::HandleCursorReleased);
	}
}

// ========== ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã‚’æ“ä½œã™ã‚‹éš›ã®åˆæœŸåŒ– ==========
void ACharacterControllerBase::OnPossess(APawn* InPawn)
{
	Super::OnPossess(InPawn);

	// è‡ªèº«ãŒæ“ä½œã™ã‚‹ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼å–å¾—
	this->CurrentCharacter = Cast<ACharacterBase>(InPawn);

	// ã‚«ãƒ¡ãƒ©ã‚¢ã‚¯ã‚¿ãƒ¼ã‚’æ¤œç´¢ï¼ˆãƒ¬ãƒ™ãƒ«å†…ã«ã‚ã‚‹æœ€åˆã®ã‚‚ã®ã‚’ä½¿ç”¨ï¼‰
	TArray<AActor*> FoundActors;
	UGameplayStatics::GetAllActorsOfClass(GetWorld(), ACameraCenterActor::StaticClass(), FoundActors);

	if (FoundActors.Num() > 0)
	{
		CameraCenterActor = Cast<ACameraCenterActor>(FoundActors[0]);
	}

	// å…¥åŠ›ãƒãƒƒãƒ”ãƒ³ã‚°ã‚’ç™»éŒ²ï¼ˆEnhanced Inputï¼‰
	TObjectPtr<UEnhancedInputLocalPlayerSubsystem> InputLocalPlayerSubsystem
		= ULocalPlayer::GetSubsystem<UEnhancedInputLocalPlayerSubsystem>(this->GetLocalPlayer());

	InputLocalPlayerSubsystem->AddMappingContext(this->CurrentMappingContext.Get(), 0);
}

// ========== ç§»å‹•å‡¦ç†ï¼ˆå‰å¾Œãƒ»å·¦å³ï¼‰ ==========
void ACharacterControllerBase::Move(const FInputActionValue& Value)
{
	const FVector2d MovementVector = Value.Get<FVector2D>();
	if (!CurrentCharacter || MovementVector.IsNearlyZero()) return;

	// ã‚«ãƒ¡ãƒ©ã® Yaw ã«åˆã‚ã›ã¦ç§»å‹•æ–¹å‘ã‚’è¨ˆç®—
	const FRotator CameraRotation = CameraCenterActor->GetActorRotation();
	const FRotator YawOnlyRotation(0.f, CameraRotation.Yaw, 0.f);

	const FVector ForwardDirection = FRotationMatrix(YawOnlyRotation).GetUnitAxis(EAxis::X);
	const FVector RightDirection = FRotationMatrix(YawOnlyRotation).GetUnitAxis(EAxis::Y);

	// âœ… å‰æ–¹ã«åœ°é¢ãŒã‚ã‚‹ã‹ãƒã‚§ãƒƒã‚¯ï¼ˆå´–ã‚¬ãƒ¼ãƒ‰ï¼‰
	if (!IsSafeToMoveInDirection(ForwardDirection * MovementVector.Y + RightDirection * MovementVector.X))
	{
		// UE_LOG(LogTemp, Warning, TEXT("â›” è¶³å…ƒã«åœ°é¢ãªã—ã€‚é€²è¡Œãƒ–ãƒ­ãƒƒã‚¯"));
		return;
	}

	// å…¥åŠ›ãƒ™ã‚¯ãƒˆãƒ«ã«å¿œã˜ã¦ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã‚’ç§»å‹•
	CurrentCharacter->AddMovementInput(ForwardDirection, MovementVector.Y);
	CurrentCharacter->AddMovementInput(RightDirection, MovementVector.X);

	// å‘ãã¯å›ºå®š
	FRotator CurrentRotation = CurrentCharacter->GetActorRotation();
	CurrentCharacter->SetActorRotation(CurrentRotation);
}

// ========== ã‚«ãƒ¡ãƒ©æ“ä½œ==========
void ACharacterControllerBase::Look(const FInputActionValue& Value)
{
	// ã‚«ãƒ¼ã‚½ãƒ«æœ‰åŠ¹ä¸­ã¯ã‚«ãƒ¡ãƒ©æ“ä½œã—ãªã„
	if (CurrentCharacter->GetVirtualCursorComponent()->bCursorEnabled)
	{
		return;
	}

	const FVector2D LookAxisVector = Value.Get<FVector2D>();

	if (CameraCenterActor)
	{
		CameraCenterActor->TurnCamera(LookAxisVector.X);
		CameraCenterActor->LookUpCamera(LookAxisVector.Y);
	}
}

// ========== ãƒ€ãƒƒã‚·ãƒ¥é–‹å§‹==========
void ACharacterControllerBase::RunStart()
{
	this->CurrentCharacter->GetCharacterMovement()->MaxWalkSpeed *= 2.0f;
}

// ========== ãƒ€ãƒƒã‚·ãƒ¥çµ‚äº† ==========
void ACharacterControllerBase::RunStop()
{
	this->CurrentCharacter->GetCharacterMovement()->MaxWalkSpeed /= 2.0f;
}

// ========== ã‚«ãƒ¡ãƒ©ã®ã‚ºãƒ¼ãƒ åˆ‡ã‚Šæ›¿ãˆï¼ˆ3æ®µéšï¼‰ ==========
void ACharacterControllerBase::HandleZoom()
{
	if (!CameraCenterActor || !CurrentCharacter) return;

	// ã‚ºãƒ¼ãƒ ãƒ¬ãƒ™ãƒ« 0â†’1â†’2â†’0 ã«å¾ªç’°
	ZoomLevel = (ZoomLevel + 1) % 3;

	// ãƒ‡ãƒãƒƒã‚°è¡¨ç¤º
	FString Msg = FString::Printf(TEXT("ZoomLevel = %d"), ZoomLevel);
	GEngine->AddOnScreenDebugMessage(-1, 2.f, FColor::Yellow, Msg);

	switch (ZoomLevel)
	{
	case 0: // é è·é›¢ãƒ»å›ºå®šè¦–ç‚¹
		CameraCenterActor->SetShouldFollowTarget(false);
		CameraCenterActor->SetTargetCenterLocation(CameraCenterActor->GetDefaultCenterLocation());
		CameraCenterActor->SetTargetOrbitRadius(CameraCenterActor->GetDefaultOrbitRadius());
		break;

	case 1: // è¿½å¾“ãƒ»ä¸­è·é›¢è¦–ç‚¹
		CameraCenterActor->SetFollowTarget(CurrentCharacter);
		CameraCenterActor->SetShouldFollowTarget(true);
		CameraCenterActor->SetTargetOrbitRadius(350.f);
		break;

	case 2: // è¿½å¾“ãƒ»è¿‘è·é›¢
		CameraCenterActor->SetTargetOrbitRadius(150.f);
		break;
	}
}

// ========== ã‚¤ãƒ³ã‚¿ãƒ©ã‚¯ãƒˆå…¥åŠ›ï¼šç›®ã®å‰ã®ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã‚’èª¿ã¹ã‚‹ãƒ»æ‹¾ã†ãªã© ==========
void ACharacterControllerBase::HandleInteract()
{
	auto* CursorComponent = CurrentCharacter->GetVirtualCursorComponent();
	if (CursorComponent->bCursorEnabled)
	{
		CursorComponent->TryInteractWithCursor();
	}
	else
	{
		CurrentCharacter->GetInteractComponent()->TryInteract();
	}
}

// ========== ã‚«ãƒ¼ã‚½ãƒ«ã‚’æœ‰åŠ¹åŒ–ï¼ˆãƒœã‚¿ãƒ³æŠ¼ã—ï¼‰ ==========
void ACharacterControllerBase::HandleCursorPressed()
{
	UE_LOG(LogTemp, Warning, TEXT("L1 pressed: HandleCursorPressed() called"));

	if (!CurrentCharacter)
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ CurrentCharacter is NULL"));
		return;
	}

	auto* CursorComponent = CurrentCharacter->GetVirtualCursorComponent();
	if (!CursorComponent)
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ VirtualCursorComponent is NULL"));
		return;
	}

	UE_LOG(LogTemp, Warning, TEXT("âœ… Calling EnableCursor()"));
	CursorComponent->EnableCursor();
}

// ========== ã‚«ãƒ¼ã‚½ãƒ«ã‚’ç„¡åŠ¹åŒ–ï¼ˆãƒœã‚¿ãƒ³é›¢ã™ï¼‰ ==========
void ACharacterControllerBase::HandleCursorReleased()
{
	if (!CurrentCharacter) return;

	auto* CursorComponent = CurrentCharacter->GetVirtualCursorComponent();
	if (CursorComponent)
	{
		CursorComponent->DisableCursor();
	}
}

void ACharacterControllerBase::UpdateLevelUI()
{
	UE_LOG(LogTemp, Warning, TEXT("ğŸŸ¢ UpdateLevelUI() called"));

	auto* GM = Cast<AGameMode_LevelBase>(UGameplayStatics::GetGameMode(this));
	if (LevelUIInstance && GM)
	{
		LevelUIInstance->SetTime(GM->GetElapsedTime());
		LevelUIInstance->SetCoinCount(GM->GetCoins());
		LevelUIInstance->SetDiamondCount(GM->GetDiamonds());
	}
	else
	{
		if (!LevelUIInstance)
			UE_LOG(LogTemp, Error, TEXT("âŒ LevelUIInstance is NULL"));
		if (!GM)
			UE_LOG(LogTemp, Error, TEXT("âŒ GameMode is NULL"));
	}
}

bool ACharacterControllerBase::IsSafeToMoveInDirection(const FVector& Direction)
{
	if (!CurrentCharacter) return true;

	
	const FVector Start = CurrentCharacter->GetActorLocation() + Direction.GetSafeNormal() * GroundForwardCheckDistance;
	const FVector End = Start - FVector(0, 0, GroundDownCheckDistance);

	FHitResult Hit;
	FCollisionQueryParams Params;
	Params.AddIgnoredActor(CurrentCharacter);

	bool bHitGround = GetWorld()->LineTraceSingleByChannel(Hit, Start, End, ECC_Visibility, Params);

#if WITH_EDITOR
	DrawDebugLine(GetWorld(), Start, End, bHitGround ? FColor::Green : FColor::Red, false, 0.2f);
#endif

	return bHitGround;
}