#include "EdgeGuardComponent.h"
#include "GameFramework/Character.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "DrawDebugHelpers.h"

UEdgeGuardComponent::UEdgeGuardComponent()
{
    PrimaryComponentTick.bCanEverTick = true;
}

void UEdgeGuardComponent::BeginPlay()
{
    Super::BeginPlay();

    ACharacter* OwnerChar = Cast<ACharacter>(GetOwner());
    if (OwnerChar)
    {
        LastSafeLocation = OwnerChar->GetActorLocation(); // åˆæœŸä½ç½®ã‚’å®‰å…¨åœ°ç‚¹ã¨ã™ã‚‹
    }
}

void UEdgeGuardComponent::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
    Super::TickComponent(DeltaTime, TickType, ThisTickFunction);

    ACharacter* OwnerChar = Cast<ACharacter>(GetOwner());
    if (!OwnerChar) return;

    FVector CurrentLocation = OwnerChar->GetActorLocation();

    // âœ… å‰æ–¹è¶³å…ƒãƒã‚§ãƒƒã‚¯ï¼ˆåœ°é¢ãŒãªã‘ã‚Œã°ç§»å‹•ã‚’æ­¢ã‚ã‚‹ï¼‰
    FVector Forward = OwnerChar->GetActorForwardVector();
    FVector Start = CurrentLocation + Forward * ForwardCheckDistance;
    FVector End = Start - FVector(0, 0, DownCheckDistance);

    FHitResult Hit;
    FCollisionQueryParams Params;
    Params.AddIgnoredActor(OwnerChar);

    bool bHasGround = GetWorld()->LineTraceSingleByChannel(Hit, Start, End, ECC_Visibility, Params);

    if (!bHasGround)
    {
        // åœ°é¢ãŒãªã‘ã‚Œã°ç§»å‹•ã‚’æ­¢ã‚ã‚‹ï¼ˆå´–ã«è½ã¡ãã†ãªå ´åˆï¼‰
        OwnerChar->GetCharacterMovement()->StopMovementImmediately();

        if (bDebugDraw)
        {
            DrawDebugLine(GetWorld(), Start, End, FColor::Red, false, DebugDrawDuration);
        }

        return; // ã“ã“ã§çµ‚äº†ï¼ˆè½ä¸‹ãƒã‚§ãƒƒã‚¯ã¯ã‚¹ã‚­ãƒƒãƒ—ï¼‰
    }

    // âœ… åœ°é¢ã«ç«‹ã£ã¦ã„ã‚Œã°å®‰å…¨åœ°ç‚¹ã‚’è¨˜éŒ²
    if (OwnerChar->GetCharacterMovement()->IsMovingOnGround())
    {
        LastSafeLocation = CurrentLocation;

        if (bDebugDraw)
        {
            DrawDebugSphere(GetWorld(), LastSafeLocation, 20.0f, 12, FColor::Green, false, DebugDrawDuration);
        }
    }

    // âœ… è½ä¸‹å¾©å¸°ï¼ˆZ ãŒé–¾å€¤ã‚’ä¸‹å›ã£ãŸã‚‰å…ƒã®ä½ç½®ã«æˆ»ã™ï¼‰
    if (CurrentLocation.Z < SafeZThreshold)
    {
        OwnerChar->SetActorLocation(LastSafeLocation);
        OwnerChar->GetCharacterMovement()->StopMovementImmediately();

        UE_LOG(LogTemp, Warning, TEXT("ğŸ›Ÿ EdgeGuard: Respawn triggered"));
    }
}