#include "ObjectBase.h"
#include "Components/StaticMeshComponent.h"
#include "Components/SkeletalMeshComponent.h"
#include "Kismet/GameplayStatics.h"
#include "Sound/SoundBase.h"
#include "Particles/ParticleSystem.h"
#include "Animation/AnimationAsset.h"
#include "TimerManager.h"
#include "Engine/World.h"

// ===============================
// ã‚³ãƒ³ã‚¹ãƒˆãƒ©ã‚¯ã‚¿ï¼šåˆæœŸå€¤è¨­å®š
// ===============================
AObjectBase::AObjectBase()
{
	PrimaryActorTick.bCanEverTick = true;

	// ãƒ¡ãƒƒã‚·ãƒ¥ã‚’ãƒ«ãƒ¼ãƒˆã«è¨­å®šï¼ˆè¦‹ãŸç›®ã®ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆï¼‰
	Mesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Mesh"));
	RootComponent = Mesh;

	// ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆå€¤
	ObjectType = EObjectType::None;
	RotationSpeed = FRotator(0.f, 90.f, 0.f);      // å›è»¢é‡ï¼ˆ1å›ã‚ãŸã‚Šï¼‰
	AutoExecuteInterval = 2.0f;                    // è‡ªå‹•å®Ÿè¡Œã®é–“éš”ï¼ˆç§’ï¼‰
	RotationSpeedDegPerSec = 180.f;                // å›è»¢ã‚¹ãƒ”ãƒ¼ãƒ‰ï¼ˆè§’åº¦/ç§’ï¼‰

	bIsPlayerInteractable = false;
	bOnlyUsableFromWidget = false;
}

// ===============================
// ã‚²ãƒ¼ãƒ é–‹å§‹æ™‚ã®åˆæœŸåŒ–
// ===============================
void AObjectBase::BeginPlay()
{
	Super::BeginPlay();

	// âœ… ãƒãƒ¼ãƒãƒ£ãƒ«ã‚«ãƒ¼ã‚½ãƒ«ã§ã®ãƒ¬ã‚¤ã‚­ãƒ£ã‚¹ãƒˆã«å¿…è¦ãªè¨­å®š
	if (Mesh)
	{
		Mesh->SetCollisionEnabled(ECollisionEnabled::QueryOnly);
		Mesh->SetCollisionResponseToChannel(ECC_Visibility, ECR_Block);
		Mesh->SetGenerateOverlapEvents(true);
	}

	// è‡ªå‹•å®Ÿè¡ŒãŒæœ‰åŠ¹ã§ã€é–“éš”ãŒæ­£ã®å€¤ãªã‚‰ã‚¿ã‚¤ãƒãƒ¼ç™»éŒ²
	if (bIsAutoExecute && AutoExecuteInterval > 0.f)
	{
		GetWorld()->GetTimerManager().SetTimer(
			AutoExecuteTimerHandle,
			this,
			&AObjectBase::StartSmoothRotation,
			AutoExecuteInterval,
			true // ãƒ«ãƒ¼ãƒ—
		);
	}
}

// ===============================
// æ¯ãƒ•ãƒ¬ãƒ¼ãƒ ã®æ›´æ–°ï¼ˆå›è»¢å‡¦ç†ï¼‰
// ===============================
void AObjectBase::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

	if (bIsRotating)
	{
		// ç¾åœ¨ã®è§’åº¦ã‹ã‚‰ç›®æ¨™è§’åº¦ã«å‘ã‘ã¦ä¸€å®šé€Ÿåº¦ã§è£œé–“
		FRotator Current = GetActorRotation();
		FRotator NewRotation = FMath::RInterpConstantTo(Current, TargetRotation, DeltaTime, RotationSpeedDegPerSec);

		SetActorRotation(NewRotation);

		// å›è»¢å®Œäº†åˆ¤å®šï¼ˆã»ã¼ä¸€è‡´ã—ãŸã‚‰çµ‚äº†ï¼‰
		if (NewRotation.Equals(TargetRotation, 0.1f))
		{
			SetActorRotation(TargetRotation); // æœ€çµ‚è£œæ­£
			bIsRotating = false;
		}
	}
}

// ===============================
// ã‚¤ãƒ³ã‚¿ãƒ©ã‚¯ãƒˆå‡¦ç†ï¼ˆãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼æ“ä½œæ™‚ï¼‰
// ===============================
void AObjectBase::OnInteract_Implementation()
{
	// ãƒ‡ãƒãƒƒã‚°ãƒ­ã‚°ï¼ˆä»»æ„ï¼‰
	UE_LOG(LogTemp, Log, TEXT("ğŸ”¹ Object Interacted: %s"), *GetName());

	// ã‚µã‚¦ãƒ³ãƒ‰å†ç”Ÿ
	if (InteractSound)
	{
		UGameplayStatics::PlaySoundAtLocation(this, InteractSound, GetActorLocation());
	}

	// ãƒ‘ãƒ¼ãƒ†ã‚£ã‚¯ãƒ«å†ç”Ÿï¼ˆã‚¨ãƒ•ã‚§ã‚¯ãƒˆä½ç½®ã¯å°‘ã—ã‚ªãƒ•ã‚»ãƒƒãƒˆå¯èƒ½ï¼‰
	if (InteractEffect)
	{
		UGameplayStatics::SpawnEmitterAtLocation(GetWorld(), InteractEffect, GetActorLocation() + EffectOffset);
	}

	// ã‚¢ãƒ‹ãƒ¡ãƒ¼ã‚·ãƒ§ãƒ³å†ç”Ÿï¼ˆSkeletalMeshãŒè¨­å®šã•ã‚Œã¦ã„ã‚Œã°ï¼‰
	if (SkeletalMesh && InteractAnimation)
	{
		SkeletalMesh->PlayAnimation(InteractAnimation, false);
	}
}

// ===============================
// è‡ªå‹•å®Ÿè¡Œç”¨ã®å‡¦ç†ï¼ˆOverrideç”¨ï¼‰
// ===============================
void AObjectBase::OnAutoExecute_Implementation()
{
	// æ´¾ç”Ÿã‚¯ãƒ©ã‚¹ã§è‡ªç”±ã«å®šç¾©å¯èƒ½
}

// ===============================
// ã‚¹ãƒ ãƒ¼ã‚ºãªå›è»¢é–‹å§‹
// ===============================
void AObjectBase::StartSmoothRotation()
{
	// ã™ã§ã«å›è»¢ä¸­ãªã‚‰ç„¡è¦–
	if (bIsRotating) return;

	// å›è»¢ç›®æ¨™ã‚’ç¾åœ¨ã®è§’åº¦ï¼‹RotationSpeedã«è¨­å®š
	TargetRotation = GetActorRotation() + RotationSpeed;
	bIsRotating = true;
}

// ===============================
// UI Widget ç”¨ã®å°‚ç”¨åˆ¤å®šé–¢æ•°
// ===============================
bool AObjectBase::IsWidgetOnlyObject() const
{
	return bOnlyUsableFromWidget;
}